name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: npm run quality

    - name: Build TypeScript to GAS
      run: ./build.sh

    - name: Setup Google Apps Script CLI
      run: npm install -g @google/clasp

    - name: Create clasp credentials
      run: |
        echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json

    - name: Create .clasp.json
      run: |
        echo '{"scriptId":"${{ secrets.GAS_SCRIPT_ID }}","rootDir":"./dist"}' > .clasp.json

    - name: Deploy to Google Apps Script
      run: |
        clasp push --force
        clasp deploy --deploymentId "${{ secrets.GAS_DEPLOYMENT_ID }}" --description "Auto-deployed from GitHub Actions - ${{ github.sha }}"

    - name: Deployment Success
      run: |
        echo "✅ Successfully deployed to Google Apps Script"
        echo "🔗 Web App URL: https://script.google.com/macros/s/${{ secrets.GAS_DEPLOYMENT_ID }}/exec"
        echo "📝 Apps Script Editor: https://script.google.com/d/${{ secrets.GAS_SCRIPT_ID }}/edit"